### ISSUE TITLE
Can the author provide the code of DCT for color image?

### ISSUE THREAD

**Issue by HeBangYan** [YiZeng623/frequency-backdoor#2]
Many thanks to the author for his excellent work! But I didn't find the relevant code for DCT in your repo, am I missing something?

**Comment by anonymous754396** [comment]
It's  in the .ipynb file in sect4 folder.

**Comment by mo666666** [comment]
@HeBangYan I also don't find the code, do you find the code of DCT for image?

**Comment by YiZeng623** [comment]
Hola, guys. Thanks again for your interest in this work! @anonymous754396 Thanks for helping with the issue;)

The DCT is in the Jupyter notebook file under section 4: [Link to the file, check out block 2](https://github.com/YiZeng623/frequency-backdoor/blob/main/Sec4_Frequency_Detection/Train_Detection.ipynb#L17).

**Comment by mo666666** [comment]
Hi, Yi Zeng, thank you for your reply. Can I use the DCT code in the Jupyter notebook to reproduce the results in Figure 1 of the original paper? If you can, would you like to provide the original code to reproduce Figure 1?
